REVOKE CONNECT, TEMP ON DATABASE vicissitude FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE vicissitude TO vicissitude_gateway, vicissitude_worker, vicissitude_migrator;
GRANT USAGE ON SCHEMA public TO vicissitude_gateway, vicissitude_worker;
GRANT ALL ON ALL TABLES IN SCHEMA public TO vicissitude_migrator;
GRANT SELECT ON schema_migrations, system_state, events, effects TO vicissitude_gateway;
GRANT SELECT, INSERT, UPDATE ON channel_capabilities TO vicissitude_gateway;
GRANT INSERT ON jobs, audit_entries TO vicissitude_gateway;
GRANT SELECT ON schema_migrations, system_state, events, jobs, character_definitions, decision_runs, effects TO vicissitude_worker;
GRANT UPDATE ON jobs, decision_runs TO vicissitude_worker;
GRANT INSERT ON decision_runs, model_calls, effects, audit_entries TO vicissitude_worker;
ALTER DEFAULT PRIVILEGES FOR ROLE vicissitude_migrator IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE vicissitude_migrator IN SCHEMA public GRANT ALL ON TABLES TO vicissitude_migrator;
