import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
	buildDeployComposeOverride,
	prepareDeployCompose,
	resolveOptionalMcpAuthPath,
	resolveOptionalOpencodeConfigPath,
	resolveOptionalProjectOpencodeConfigPath,
	resolveWorkspaceNodeModulesMounts,
} from "./prepare-deploy-compose.ts";

describe("prepare-deploy-compose", () => {
	test("opencode.json がない場合は空の override を生成する", () => {
		expect(buildDeployComposeOverride(null)).toBe(
			"# Generated by scripts/prepare-deploy-compose.ts. Do not edit.\nservices: {}\n",
		);
	});

	test("opencode.json がある場合だけ bot に read-only bind mount を追加する", () => {
		const compose = buildDeployComposeOverride("/home/example/.config/opencode/opencode.json");

		expect(compose).toContain("services:\n  bot:");
		expect(compose).toContain('source: "/home/example/.config/opencode/opencode.json"');
		expect(compose).toContain('target: "/app/.config/opencode/opencode.json"');
		expect(compose).toContain("read_only: true");
	});

	test("project root の opencode.json と mcp-auth.json を bot に read-only bind mount する", () => {
		const compose = buildDeployComposeOverride(null, [], {
			mcpAuthPath: "/home/example/.local/share/opencode/mcp-auth.json",
			projectOpencodeConfigPath: "/repo/opencode.json",
		});

		expect(compose).toContain("services:\n  bot:");
		expect(compose).toContain('source: "/repo/opencode.json"');
		expect(compose).toContain('target: "/app/opencode.json"');
		expect(compose).toContain('source: "/home/example/.local/share/opencode/mcp-auth.json"');
		expect(compose).toContain('target: "/app/.local/share/opencode/mcp-auth.json"');
		expect(compose).toContain("read_only: true");
	});

	test("workspace node_modules volume を installer/builder/bot に追加する", () => {
		const compose = buildDeployComposeOverride(null, [
			{
				volumeName: "deploy-packages-mcp-node-modules",
				targetPath: "/app/packages/mcp/node_modules",
			},
		]);

		expect(compose).toContain("volumes:\n  deploy-packages-mcp-node-modules:\n");
		expect(compose).toContain(
			"  installer:\n    volumes:\n      - deploy-packages-mcp-node-modules:/app/packages/mcp/node_modules\n",
		);
		expect(compose).toContain(
			"  builder:\n    volumes:\n      - deploy-packages-mcp-node-modules:/app/packages/mcp/node_modules:ro\n",
		);
		expect(compose).toContain(
			"  bot:\n    volumes:\n      - deploy-packages-mcp-node-modules:/app/packages/mcp/node_modules:ro\n",
		);
	});

	test("workspace node_modules volume と opencode mount を bot に併記する", () => {
		const compose = buildDeployComposeOverride("/home/example/.config/opencode/opencode.json", [
			{
				volumeName: "deploy-apps-discord-node-modules",
				targetPath: "/app/apps/discord/node_modules",
			},
		]);

		expect(compose).toContain(
			"      - deploy-apps-discord-node-modules:/app/apps/discord/node_modules:ro\n      - type: bind\n",
		);
		expect(compose).toContain('source: "/home/example/.config/opencode/opencode.json"');
	});

	test("ホーム配下に opencode.json がない場合は null を返す", () => {
		const homeDir = makeTempDir();
		try {
			expect(resolveOptionalOpencodeConfigPath(homeDir)).toBeNull();
		} finally {
			rmSync(homeDir, { recursive: true, force: true });
		}
	});

	test("ホーム配下の opencode.json が regular file ならそのパスを返す", () => {
		const homeDir = makeTempDir();
		const configPath = join(homeDir, ".config", "opencode", "opencode.json");
		try {
			mkdirSync(join(homeDir, ".config", "opencode"), { recursive: true });
			writeFileSync(configPath, "{}\n");

			expect(resolveOptionalOpencodeConfigPath(homeDir)).toBe(configPath);
		} finally {
			rmSync(homeDir, { recursive: true, force: true });
		}
	});

	test("project root の opencode.json が regular file ならそのパスを返す", () => {
		const rootDir = makeTempDir();
		const configPath = join(rootDir, "opencode.json");
		try {
			writeFileSync(configPath, "{}\n");

			expect(resolveOptionalProjectOpencodeConfigPath(rootDir)).toBe(configPath);
		} finally {
			rmSync(rootDir, { recursive: true, force: true });
		}
	});

	test("ホーム配下の mcp-auth.json が regular file ならそのパスを返す", () => {
		const homeDir = makeTempDir();
		const mcpAuthPath = join(homeDir, ".local", "share", "opencode", "mcp-auth.json");
		try {
			mkdirSync(join(homeDir, ".local", "share", "opencode"), { recursive: true });
			writeFileSync(mcpAuthPath, "{}\n");

			expect(resolveOptionalMcpAuthPath(homeDir)).toBe(mcpAuthPath);
		} finally {
			rmSync(homeDir, { recursive: true, force: true });
		}
	});

	test("opencode.json の位置が directory なら deploy を止める", () => {
		const homeDir = makeTempDir();
		try {
			mkdirSync(join(homeDir, ".config", "opencode", "opencode.json"), { recursive: true });

			expect(() => resolveOptionalOpencodeConfigPath(homeDir)).toThrow("not a regular file");
		} finally {
			rmSync(homeDir, { recursive: true, force: true });
		}
	});

	test("prepareDeployCompose は生成先に override を書く", async () => {
		const homeDir = makeTempDir();
		const rootDir = makeTempDir();
		const outputPath = join(homeDir, "generated", "compose.deploy.yaml");
		try {
			writeFileSync(
				join(rootDir, "package.json"),
				JSON.stringify({ workspaces: ["packages/*", "apps/*"] }),
			);
			mkdirSync(join(rootDir, "packages", "shared"), { recursive: true });
			mkdirSync(join(rootDir, "apps", "discord"), { recursive: true });
			writeFileSync(join(rootDir, "packages", "shared", "package.json"), "{}\n");
			writeFileSync(join(rootDir, "apps", "discord", "package.json"), "{}\n");

			const result = prepareDeployCompose({ homeDir, outputPath, rootDir });
			const text = await Bun.file(outputPath).text();

			expect(result).toEqual({
				outputPath,
				opencodeConfigPath: null,
				projectOpencodeConfigPath: null,
				mcpAuthPath: null,
				workspaceNodeModulesMounts: [
					{
						volumeName: "deploy-packages-shared-node-modules",
						targetPath: "/app/packages/shared/node_modules",
					},
					{
						volumeName: "deploy-apps-discord-node-modules",
						targetPath: "/app/apps/discord/node_modules",
					},
				],
			});
			expect(text).toContain("deploy-packages-shared-node-modules");
			expect(text).toContain("deploy-apps-discord-node-modules");
		} finally {
			rmSync(homeDir, { recursive: true, force: true });
			rmSync(rootDir, { recursive: true, force: true });
		}
	});

	test("workspace 定義から node_modules mount を解決する", () => {
		const rootDir = makeTempDir();
		try {
			writeFileSync(join(rootDir, "package.json"), JSON.stringify({ workspaces: ["packages/*"] }));
			mkdirSync(join(rootDir, "packages", "shared"), { recursive: true });
			mkdirSync(join(rootDir, "packages", "ignored"), { recursive: true });
			writeFileSync(join(rootDir, "packages", "shared", "package.json"), "{}\n");

			expect(resolveWorkspaceNodeModulesMounts(rootDir)).toEqual([
				{
					volumeName: "deploy-packages-shared-node-modules",
					targetPath: "/app/packages/shared/node_modules",
				},
			]);
		} finally {
			rmSync(rootDir, { recursive: true, force: true });
		}
	});
});

function makeTempDir(): string {
	return mkdtempSync(join(tmpdir(), "vicissitude-deploy-"));
}
