import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const DEFAULT_OUTPUT_PATH = ".generated/compose.deploy.yaml";
const OPENCODE_CONFIG_TARGET = "/app/.config/opencode/opencode.json";

export interface WorkspaceNodeModulesMount {
	volumeName: string;
	targetPath: string;
}

export interface DeployComposePreparation {
	outputPath: string;
	opencodeConfigPath: string | null;
	workspaceNodeModulesMounts: WorkspaceNodeModulesMount[];
}

export function prepareDeployCompose(
	options: {
		homeDir?: string;
		outputPath?: string;
		rootDir?: string;
	} = {},
): DeployComposePreparation {
	const outputPath = options.outputPath ?? DEFAULT_OUTPUT_PATH;
	const homeDir = options.homeDir ?? process.env.HOME ?? homedir();
	const rootDir = options.rootDir ?? process.cwd();
	const opencodeConfigPath = resolveOptionalOpencodeConfigPath(homeDir);
	const workspaceNodeModulesMounts = resolveWorkspaceNodeModulesMounts(rootDir);

	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(
		outputPath,
		buildDeployComposeOverride(opencodeConfigPath, workspaceNodeModulesMounts),
	);

	return { outputPath, opencodeConfigPath, workspaceNodeModulesMounts };
}

export function resolveOptionalOpencodeConfigPath(homeDir: string): string | null {
	const configPath = join(homeDir, ".config", "opencode", "opencode.json");
	try {
		const stat = statSync(configPath);
		if (stat.isFile()) return configPath;
		throw new Error(`optional opencode config exists but is not a regular file: ${configPath}`);
	} catch (error) {
		if (isMissingPathError(error)) return null;
		throw error;
	}
}

export function resolveWorkspaceNodeModulesMounts(rootDir: string): WorkspaceNodeModulesMount[] {
	const packageJson = JSON.parse(readFileSync(join(rootDir, "package.json"), "utf8")) as {
		workspaces?: unknown;
	};
	const workspacePatterns = parseWorkspacePatterns(packageJson.workspaces);

	return workspacePatterns.flatMap((pattern) => {
		const baseDir = parseSingleLevelWorkspacePattern(pattern);
		return readdirSync(join(rootDir, baseDir), { withFileTypes: true })
			.filter((entry) => entry.isDirectory())
			.map((entry) => join(baseDir, entry.name))
			.filter((workspacePath) => {
				try {
					return statSync(join(rootDir, workspacePath, "package.json")).isFile();
				} catch (error) {
					if (isMissingPathError(error)) return false;
					throw error;
				}
			})
			.toSorted()
			.map((workspacePath) => ({
				volumeName: `deploy-${workspacePath.replaceAll("/", "-")}-node-modules`,
				targetPath: `/app/${workspacePath}/node_modules`,
			}));
	});
}

export function buildDeployComposeOverride(
	opencodeConfigPath: string | null,
	workspaceNodeModulesMounts: WorkspaceNodeModulesMount[] = [],
): string {
	const header = "# Generated by scripts/prepare-deploy-compose.ts. Do not edit.\n";
	const serviceEntries = buildServiceEntries(opencodeConfigPath, workspaceNodeModulesMounts);
	const volumeEntries = buildVolumeEntries(workspaceNodeModulesMounts);
	if (serviceEntries.length === 0 && volumeEntries.length === 0) return `${header}services: {}\n`;

	return `${header}${volumeEntries.join("")}services:\n${serviceEntries.join("")}`;
}

function buildServiceEntries(
	opencodeConfigPath: string | null,
	workspaceNodeModulesMounts: WorkspaceNodeModulesMount[],
): string[] {
	const entries: string[] = [];
	if (workspaceNodeModulesMounts.length > 0) {
		entries.push(buildWorkspaceNodeModulesService("installer", workspaceNodeModulesMounts, false));
		entries.push(buildWorkspaceNodeModulesService("builder", workspaceNodeModulesMounts, true));
	}
	if (workspaceNodeModulesMounts.length > 0 || opencodeConfigPath !== null) {
		entries.push(buildBotService(opencodeConfigPath, workspaceNodeModulesMounts));
	}
	return entries;
}

function buildWorkspaceNodeModulesService(
	serviceName: string,
	mounts: WorkspaceNodeModulesMount[],
	readOnly: boolean,
): string {
	const suffix = readOnly ? ":ro" : "";
	return `  ${serviceName}:\n    volumes:\n${mounts
		.map((mount) => `      - ${mount.volumeName}:${mount.targetPath}${suffix}\n`)
		.join("")}`;
}

function buildBotService(
	opencodeConfigPath: string | null,
	workspaceNodeModulesMounts: WorkspaceNodeModulesMount[],
): string {
	const lines = [`  bot:\n`, `    volumes:\n`];
	for (const mount of workspaceNodeModulesMounts) {
		lines.push(`      - ${mount.volumeName}:${mount.targetPath}:ro\n`);
	}
	if (opencodeConfigPath !== null) {
		lines.push(
			`      - type: bind\n`,
			`        source: ${yamlString(opencodeConfigPath)}\n`,
			`        target: ${yamlString(OPENCODE_CONFIG_TARGET)}\n`,
			`        read_only: true\n`,
		);
	}
	return lines.join("");
}

function buildVolumeEntries(workspaceNodeModulesMounts: WorkspaceNodeModulesMount[]): string[] {
	if (workspaceNodeModulesMounts.length === 0) return [];
	return [
		`volumes:\n${workspaceNodeModulesMounts.map((mount) => `  ${mount.volumeName}:\n`).join("")}`,
	];
}

function parseWorkspacePatterns(workspaces: unknown): string[] {
	if (Array.isArray(workspaces) && workspaces.every((item) => typeof item === "string")) {
		return workspaces;
	}
	throw new Error("package.json workspaces must be a string array");
}

function parseSingleLevelWorkspacePattern(pattern: string): string {
	if (!pattern.endsWith("/*") || pattern.slice(0, -2).includes("*")) {
		throw new Error(`unsupported workspace pattern: ${pattern}`);
	}
	return pattern.slice(0, -2);
}

function yamlString(value: string): string {
	return JSON.stringify(value);
}

function isMissingPathError(error: unknown): boolean {
	return (
		error instanceof Error &&
		"code" in error &&
		(error.code === "ENOENT" || error.code === "ENOTDIR")
	);
}

if (import.meta.main) {
	try {
		const result = prepareDeployCompose();
		if (result.opencodeConfigPath) {
			console.log(
				`[deploy] optional opencode config mounted: ${result.opencodeConfigPath} -> ${OPENCODE_CONFIG_TARGET}`,
			);
		} else {
			console.log("[deploy] optional opencode config not found; mount skipped");
		}
		console.log(`[deploy] compose override prepared: ${result.outputPath}`);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		console.error(`[deploy] compose override preparation failed: ${message}`);
		process.exit(1);
	}
}
