import { mkdirSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const DEFAULT_OUTPUT_PATH = ".generated/compose.deploy.yaml";
const OPENCODE_CONFIG_TARGET = "/app/.config/opencode/opencode.json";

export interface DeployComposePreparation {
	outputPath: string;
	opencodeConfigPath: string | null;
}

export function prepareDeployCompose(
	options: {
		homeDir?: string;
		outputPath?: string;
	} = {},
): DeployComposePreparation {
	const outputPath = options.outputPath ?? DEFAULT_OUTPUT_PATH;
	const homeDir = options.homeDir ?? process.env.HOME ?? homedir();
	const opencodeConfigPath = resolveOptionalOpencodeConfigPath(homeDir);

	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, buildDeployComposeOverride(opencodeConfigPath));

	return { outputPath, opencodeConfigPath };
}

export function resolveOptionalOpencodeConfigPath(homeDir: string): string | null {
	const configPath = join(homeDir, ".config", "opencode", "opencode.json");
	try {
		const stat = statSync(configPath);
		if (stat.isFile()) return configPath;
		throw new Error(`optional opencode config exists but is not a regular file: ${configPath}`);
	} catch (error) {
		if (isMissingPathError(error)) return null;
		throw error;
	}
}

export function buildDeployComposeOverride(opencodeConfigPath: string | null): string {
	const header = "# Generated by scripts/prepare-deploy-compose.ts. Do not edit.\n";
	if (opencodeConfigPath === null) return `${header}services: {}\n`;

	return `${header}services:
  bot:
    volumes:
      - type: bind
        source: ${yamlString(opencodeConfigPath)}
        target: ${yamlString(OPENCODE_CONFIG_TARGET)}
        read_only: true
`;
}

function yamlString(value: string): string {
	return JSON.stringify(value);
}

function isMissingPathError(error: unknown): boolean {
	return (
		error instanceof Error &&
		"code" in error &&
		(error.code === "ENOENT" || error.code === "ENOTDIR")
	);
}

if (import.meta.main) {
	try {
		const result = prepareDeployCompose();
		if (result.opencodeConfigPath) {
			console.log(
				`[deploy] optional opencode config mounted: ${result.opencodeConfigPath} -> ${OPENCODE_CONFIG_TARGET}`,
			);
		} else {
			console.log("[deploy] optional opencode config not found; mount skipped");
		}
		console.log(`[deploy] compose override prepared: ${result.outputPath}`);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		console.error(`[deploy] compose override preparation failed: ${message}`);
		process.exit(1);
	}
}
