import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
	buildDeployComposeOverride,
	prepareDeployCompose,
	resolveOptionalOpencodeConfigPath,
} from "./prepare-deploy-compose.ts";

describe("prepare-deploy-compose", () => {
	test("opencode.json がない場合は空の override を生成する", () => {
		expect(buildDeployComposeOverride(null)).toBe(
			"# Generated by scripts/prepare-deploy-compose.ts. Do not edit.\nservices: {}\n",
		);
	});

	test("opencode.json がある場合だけ bot に read-only bind mount を追加する", () => {
		const compose = buildDeployComposeOverride("/home/example/.config/opencode/opencode.json");

		expect(compose).toContain("services:\n  bot:");
		expect(compose).toContain('source: "/home/example/.config/opencode/opencode.json"');
		expect(compose).toContain('target: "/app/.config/opencode/opencode.json"');
		expect(compose).toContain("read_only: true");
	});

	test("ホーム配下に opencode.json がない場合は null を返す", () => {
		const homeDir = makeTempDir();
		try {
			expect(resolveOptionalOpencodeConfigPath(homeDir)).toBeNull();
		} finally {
			rmSync(homeDir, { recursive: true, force: true });
		}
	});

	test("ホーム配下の opencode.json が regular file ならそのパスを返す", () => {
		const homeDir = makeTempDir();
		const configPath = join(homeDir, ".config", "opencode", "opencode.json");
		try {
			mkdirSync(join(homeDir, ".config", "opencode"), { recursive: true });
			writeFileSync(configPath, "{}\n");

			expect(resolveOptionalOpencodeConfigPath(homeDir)).toBe(configPath);
		} finally {
			rmSync(homeDir, { recursive: true, force: true });
		}
	});

	test("opencode.json の位置が directory なら deploy を止める", () => {
		const homeDir = makeTempDir();
		try {
			mkdirSync(join(homeDir, ".config", "opencode", "opencode.json"), { recursive: true });

			expect(() => resolveOptionalOpencodeConfigPath(homeDir)).toThrow("not a regular file");
		} finally {
			rmSync(homeDir, { recursive: true, force: true });
		}
	});

	test("prepareDeployCompose は生成先に override を書く", async () => {
		const homeDir = makeTempDir();
		const outputPath = join(homeDir, "generated", "compose.deploy.yaml");
		try {
			const result = prepareDeployCompose({ homeDir, outputPath });
			const text = await Bun.file(outputPath).text();

			expect(result).toEqual({ outputPath, opencodeConfigPath: null });
			expect(text).toContain("services: {}");
		} finally {
			rmSync(homeDir, { recursive: true, force: true });
		}
	});
});

function makeTempDir(): string {
	return mkdtempSync(join(tmpdir(), "vicissitude-deploy-"));
}
